config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :time_entries
  resources :developers
  resources :logins

end

app/models/developer.rb
class Developer < ActiveRecord::Base
  has_many :time_entries
  has_secure_password


  def hours_worked
    total_hours = 0.0
    start_week = Time.now.beginning_of_week
    end_week = Time.now.end_of_week
    time_entries.each do |t|
      if start_week..end_week.include?(time.worked_on)
        total_hours += t.duration
      end
    end
    return total_hours
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :time_entries
end

app/models/time_entry.rb
class TimeEntry < ActiveRecord::Base
  belongs_to :developer
  belongs_to :project
  validates :developer, presence: true
  validates :project, presence: true

  def time_entry
    total_time = 0.0
    time_entries.each do |t|
      total_hours += t.duration
    end
    return total_hours
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  before_action :check_logged_in
  before_action :set_developer, only: [:show, :edit, :update, :destroy]

  def index
    @developers = Developer.all
  end

  def show
  end

  def new
    @developer = Developer.new
  end

  def create
    @developer = Developer.new(developer_params)

    respond_to do |format|
      if @developer.save
        format.html { redirect_to @developer, notice: 'developer was successfully created.' }
        format.json { render :show, status: :created, location: @developer }
      else
        format.html { render :new }
        format.json { render json: @developer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @developer.update(developer_params)
        format.html { redirect_to @developer, notice: 'Developer was successfully updated.' }
        format.json { render :show, status: :ok, location: @developer }
      else
        format.html { render :edit }
        format.json { render json: @developer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @developer.destroy
    respond_to do |format|
      format.html { redirect_to developers_url, notice: 'Developer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def edit
  end

  private def check_logged_in
    redirect_to logins_path unless session[:developer_id]
  end

  private def developer_params
    params.require(:developer).permit(:email, :password)
  end

  private def set_developer
    @developer = Developer.find_by_id(params[:id])
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController


  def new
  end
  def create
    developer = Developer.find_by_email(params[:email])
    if developer && developer.authenticate(params[:password])
      session[:developer_id] = developer.id
      flash[:notice] = "Welcome!"
      redirect_to developers_path
    else
      flash.now[:notice] = "Please re-enter credentials"
      render :new
    end
  end

  def destroy
    session[:developer_id] = nil
    redirect_to login_path
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :check_logged_in
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all

  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def edit
  end

  private def check_logged_in
    redirect_to logins_path unless session[:developer_id]
  end

  private def project_params
    params.require(:project).permit(:name, :max_hours)
  end

  private def set_project
    @project = Project.find_by_id(params[:id])
  end
end

app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
  before_action :check_logged_in
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @time_entries = TimeEntry.all
  end

  def show
  end

  def new
    @time_entry = TimeEntry.new
  end

  def create
    @time_entry = TimeEntry.new(time_entry_params)
    respond_to do |format|
      if @time_entry.save
        format.html { redirect_to @time_entry, notice: 'time entry was successfully created.' }
        format.json { render :show, status: :created, location: @time_entry }
      else
        format.html { render :new }
        format.json { render json: @time_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @time_entry.update(time_entry_params)
        format.html { redirect_to @time_entry, notice: 'Time entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_entry }
      else
        format.html { render :edit }
        format.json { render json: @time_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @time_entry.destroy
    respond_to do |format|
      format.html { redirect_to time_entries_url, notice: 'Time entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def edit
  end

  private def check_logged_in
    redirect_to logins_path unless session[:developer_id]
  end

  private def time_entry_params
    params.require(:time_entry).permit(:duration, :project_id, :developer_id, :worked_on)
  end

  private def set_time_entry
    @time_entry = TimeEntry.find_by_id(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

app/views/developers/_form.html.erb
<%= form_for(@developer) do |f| %>
  <% if @developer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@developer.errors.count, "error") %> prohibited this developer from being saved:</h2>
    </div>
    <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/developers/create.html.erb
<h1>Developers#create</h1>
<p>Find me in app/views/developers/create.html.erb</p>

app/views/developers/destroy.html.erb
<h1>Developers#destroy</h1>
<p>Find me in app/views/developers/destroy.html.erb</p>

app/views/developers/edit.html.erb
<h1>Edit Developer</h1>

<%= render 'form' %>

<%= link_to 'Back', developers_path %>

app/views/developers/index.html.erb
<h1>Developers interested in world domination:</h1>

<table>
  <tbody>
    <% @developers.each do |developer| %>
    <tr>
      <td><%= developer.email %></td>
      <td><%= developer.hours_worked %></td>
      <td><%= link_to 'Edit', edit_developer_path(developer) %></td>
      <td><%= link_to 'Destroy', developer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<br>



<%= link_to 'Go to the Project home page', projects_path %>
<%= link_to 'View all timesheets', time_entries_path %>
<%= link_to 'Create a new developer', new_developer_path %>

app/views/developers/new.html.erb
<h1>New Developer</h1>

<%= render 'form' %>

<%= link_to 'Back', new_developer_path %>

app/views/developers/show.html.erb
<h1>Developer Information</h1>
<p><%= @developer.email %></p>


<%= link_to 'Return to Developer List', developers_path  %>

app/views/developers/update.html.erb
<h1>Developers#update</h1>
<p>Find me in app/views/developers/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OnTheClock</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= notice %>
<%= yield %>

</body>
</html>

app/views/logins/new.html.erb
<h1>On The Clock</h1>
<p>A time tracking application for software developers</p>

<%= form_tag logins_path do %>
  <%= text_field_tag :email, nil, placeholder: "email address" %>
  <%= password_field_tag :password, nil, placeholder: "password" %>
  <%= submit_tag "seize the day" %>
<% end %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
<% if @project.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
</div>
<% end %>

<div class="field">
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</div>

<div class="field">
  <%= f.label :max_hours %><br>
  <%= f.text_field :max_hours %>
</div>

<div class="actions">
  <%= f.submit %>
</div>

<% end %>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>All the projects worth considering:</h1>
<h3>Project List & Max Hours Alloted</h3>

<table>
  <tbody>
    <% @projects.each do |project| %>
    <tr>
      <td><%= project.name %></td>
      <td><%= project.max_hours %></td>
      <td><%= link_to 'Edit', edit_project_path(project) %></td>
      <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to 'Add New Project', new_project_path %></p>
<p><%= link_to 'View all timesheets', time_entries_path %></p>
<p><%= link_to 'Create a new developer', new_developer_path %></p>

app/views/projects/new.html.erb
<h1>New Projects </h1>
<%= render 'form' %>

<%= link_to 'Back', new_project_path %>

app/views/projects/show.html.erb
<h1>Project Information</h1>


<h4>Project Name</h4>
<p><%= @project.name %></p>
<h4>Max hours allotted</h4>
<p><%= @project.max_hours %></p>
<%= link_to 'Return to Project List', projects_path  %>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>

app/views/time_entries/_form.html.erb
<%= form_for(@time_entry) do |f| %>
<% if @time_entry.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@time_entry.errors.count, "error") %> prohibited this time entry from being saved:</h2>
</div>
<% end %>

<div class="field">
  <%= f.label :duration_to_the_quarter_hour %><br>
  <%= f.number_field :duration %>
</div>

<div class="field">
  <%= f.label :project_id %><br>
  <%= f.number_field :project_id %>
</div>

<div class="field">
  <%= f.label :your_developer_id %><br>
  <%= f.number_field :developer_id %>
</div>

<div class="field">
  <%= f.label :worked_on %><br>
  <%= f.date_field :worked_on %>
</div>

<div class="actions">
  <%= f.submit %>
</div>

<% end %>

app/views/time_entries/create.html.erb
<h1>TimeEntries#create</h1>
<p>Find me in app/views/time_entries/create.html.erb</p>

app/views/time_entries/destroy.html.erb
<h1>TimeEntries#destroy</h1>
<p>Find me in app/views/time_entries/destroy.html.erb</p>

app/views/time_entries/edit.html.erb
<h1>Edit Time Entry</h1>

<%= render 'form' %>

<%= link_to 'Back', edit_time_entry_path %>

app/views/time_entries/index.html.erb
<h1>All Time Entries</h1>


<table>
  <tbody>
    <% @time_entries.each do |time| %>
    <tr>
      <td><%= time.duration %></td>
      <td><%= time.project.name %></td>
      <td><%= time.developer.email %></td>
      <td><%= time.worked_on %></td>
      <td><%= link_to 'Edit', edit_time_entry_path(time) %></td>
      <td><%= link_to 'Destroy', time, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Add New Time Project', new_time_entry_path %>


<%= link_to 'Return to the Project home page', projects_path %>

app/views/time_entries/new.html.erb
<h1>New Time Entry </h1>
<%= render 'form' %>

<%= link_to 'Back', new_time_entry_path %>

app/views/time_entries/show.html.erb
<h1>Time Entry was created</h1>

<h3>Now get back to work.</h3>

<%= link_to 'Return to Time Entries List', new_time_entry_path  %>

app/views/time_entries/update.html.erb
<h1>TimeEntries#update</h1>
<p>Find me in app/views/time_entries/update.html.erb</p>